[package]
name = "streamflow-sdk"
version = "0.6.0-alpha.8"
license = "MIT"
description = "Rust SDK to interact with Streamflow protocol"
repository = "https://github.com/streamflow-finance/rust-sdk"
edition = "2021"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-lang = "0.27.0"
anchor-spl = "0.27.0"
borsh = "0.10.2"
